[package]
name = "cargo-subcommand"
version = "0.4.5"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Library for creating cargo subcommands."
repository = "https://github.com/dvc94ch/cargo-subcommand"
license = "ISC"

[dependencies]
serde = { version = "1.0.111", features = ["derive"] }
toml = "0.5.6"
